# Generated by Django 3.2.6 on 2021-09-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorPedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('numero', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=30)),
                ('fecha_apertura', models.DateTimeField()),
                ('estado', models.CharField(max_length=30)),
                ('unidad_ejecutora', models.IntegerField()),
                ('aperturado', models.BooleanField()),
            ],
        ),
    ]
