# Generated by Django 3.2.6 on 2021-09-06 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorPedidos', '0002_licitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
    ]
