# Generated by Django 3.2.6 on 2021-09-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorPedidos', '0004_auto_20210907_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='licitacion',
            field=models.ManyToManyField(null=True, to='gestorPedidos.Licitacion'),
        ),
    ]
