# Generated by Django 3.2.6 on 2021-10-22 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorPedidos', '0006_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='licitacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestorPedidos.licitacion'),
            preserve_default=False,
        ),
    ]
